site_name: Async Storage
repo_url: https://github.com/react-native-async-storage/async-storage
site_url: https://react-native-async-storage.github.io/

nav:
  - Overview: index.md
  - Installation: Installation.md
  - Usage: Usage.md
  - API: API.md
  - Advanced:
      - Next Storage: advanced/Next.md
      - Backup: advanced/Backup.md
      - Brownfield Integration: advanced/BrownfieldIntegration.md
      - Dedicated Executor: advanced/DedicatedExecutor.md
      - Increase Database Size: advanced/IncreaseDbSize.md
      - Jest integration: advanced/Jest-integration.md
      - Where data is stored: advanced/Where-data-stored.md
      - Known limits: advanced/Limits.md
  - Debugging:
      - Community packages: debugging/communityPackages.md
  - Help:
      - Troubleshooting: help/Troubleshooting.md


theme:
  name: material
  palette:
    primary: custom
    accent: custom
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      name: Async Storage
      link: https://github.com/react-native-async-storage/async-storage
  version:
    provider: mike
