name: PR review
on:
  pull_request:
jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-name: [lint, ts, format]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Install dependencies
        run: yarn
      - name: test ${{ matrix.test-name }}
        run: yarn test:${{ matrix.test-name }}

  shared-storage-tests:
    name: shared-storage tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15-xlarge, ubuntu-24.04]
        testName:
          [cleanTestAndroidHostTest, macosArm64Test, iosSimulatorArm64Test]
        exclude:
          - testName: cleanTestAndroidHostTest
            os: macos-15-xlarge
          - testName: macosArm64Test
            os: ubuntu-24.04
          - testName: iosSimulatorArm64Test
            os: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Run test ${{ matrix.testName }}
        run: |
          ./gradlew ${{ matrix.testName }}
