name: Release
permissions:
  id-token: write
  contents: read
on:
  push:
    branches: [main]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: "false"
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build Android native library
        run: bash ./scripts/build-native-lib.sh android
      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: packages/async-storage/android/local_repo

  build-apple:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: "false"
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build Apple native library
        run: bash ./scripts/build-native-lib.sh apple
      - name: Upload Apple artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apple-artifacts
          path: packages/async-storage/apple-frameworks

  release:
    runs-on: ubuntu-latest
    needs: [build-android, build-apple]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: "false"
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Install dependencies
        run: yarn
      - name: Download Android artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-artifacts
          path: packages/async-storage/android/local_repo
      - name: Download Apple artifacts
        uses: actions/download-artifact@v4
        with:
          name: apple-artifacts
          path: packages/async-storage/apple-frameworks
      - name: Version or release packages
        uses: changesets/action@v1
        with:
          title: "release: version packages"
          commit: "release: version packages"
          setupGitUser: "false"
          publish: "yarn release:publish"
          version: "yarn release:version"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          GITHUB_NAME: ${{ vars.GH_BOT_NAME }}
          GITHUB_EMAIL: ${{ vars.GH_BOT_EMAIL }}
          NPM_TOKEN: "" # https://github.com/changesets/changesets/issues/1152#issuecomment-3765490009
          NPM_CONFIG_PROVENANCE: true
